name: Sync Bologna Repo

on:
  push:
    branches:
      - bologna

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3
        with:
          persist-credentials: "false"

      - name: Push to public Hello FPGA repository
        run: |
          git config --global user.email "hello-fpga@belfortlabs.com"
          git config --global user.name "Hello FPGA"
          git clone --branch bologna https://github.com/belfortlabs/hello-fpga.git
          cd hello-fpga
          git remote add internal https://belfortlabs:${{ env.access-token }}@github.com/belfortlabs/hello-fpga-internal.git
          git remote update
          git merge internal/bologna
          # Remove workflow files from the index (but keep them in working directory)
          git rm -r --cached .github/workflows/ || true
          git push origin bologna
        env:
          access-token: ${{ secrets.HELLO_FPGA_PAT }}
